import type { GalleryItem } from "@/components/shared/GalleryGrid";

export const tattooGalleryItems: GalleryItem[] = [
  { id: "t1",  bg: "#2d2926", alt: "Fine line botanical arm",        height: "360px", style: "Fine Line" },
  { id: "t2",  bg: "#252220", alt: "Geometric shoulder piece",       height: "260px", style: "Fine Line" },
  { id: "t3",  bg: "#302b28", alt: "Delicate floral wrist",          height: "440px", style: "Fine Line" },
  { id: "t4",  bg: "#1e1c1a", alt: "Minimal line ankle",             height: "300px", style: "Fine Line" },
  { id: "t5",  bg: "#2a2622", alt: "Botanical rib cage",             height: "480px", style: "Fine Line" },
  { id: "t6",  bg: "#332e2b", alt: "Fine line back piece",           height: "220px", style: "Fine Line" },
  { id: "t7",  bg: "#242120", alt: "Geometric forearm",              height: "340px", style: "Fine Line" },
  { id: "t8",  bg: "#2e2a27", alt: "Micro floral collarbone",        height: "460px", style: "Micro-realism" },
  { id: "t9",  bg: "#1c1a18", alt: "Abstract minimal thigh",         height: "280px", style: "Fine Line" },
  { id: "t10", bg: "#312c29", alt: "Dotwork mandala",                height: "380px", style: "Fine Line" },
  { id: "t11", bg: "#272320", alt: "Fine line hand",                 height: "240px", style: "Fine Line" },
  { id: "t12", bg: "#2c2825", alt: "Botanical sleeve detail",        height: "400px", style: "Micro-realism" },
  { id: "t13", bg: "#1f1d1b", alt: "Minimal neck piece",             height: "320px", style: "Fine Line" },
  { id: "t14", bg: "#342f2c", alt: "Geometric chest",                height: "200px", style: "Fine Line" },
  { id: "t15", bg: "#252220", alt: "Delicate spine tattoo",          height: "460px", style: "Fine Line" },
  { id: "t16", bg: "#2b2724", alt: "Fine line portrait",             height: "260px", style: "Realism" },
  { id: "t17", bg: "#302b28", alt: "Botanical upper arm",            height: "360px", style: "Micro-realism" },
  { id: "t18", bg: "#232120", alt: "Minimalist symbol finger",       height: "300px", style: "Fine Line" },
  { id: "t19", bg: "#28241f", alt: "Micro portrait wrist",           height: "460px", style: "Micro-realism" },
  { id: "t20", bg: "#1e1c1a", alt: "Geometric sternum",              height: "220px", style: "Fine Line" },
  { id: "t21", bg: "#2f2b27", alt: "Realistic rose forearm",         height: "400px", style: "Realism" },
  { id: "t22", bg: "#252220", alt: "Botanical shoulder blade",       height: "280px", style: "Fine Line" },
  { id: "t23", bg: "#342f2c", alt: "Fine line ribcage script",       height: "340px", style: "Fine Line" },
  { id: "t24", bg: "#1c1a18", alt: "Micro realism butterfly",        height: "480px", style: "Micro-realism" },
  { id: "t25", bg: "#2a2622", alt: "Geometric full sleeve",          height: "380px", style: "Fine Line" },
  { id: "t26", bg: "#312c29", alt: "Minimalist mountain",            height: "240px", style: "Fine Line" },
  { id: "t27", bg: "#272320", alt: "Botanical calf piece",           height: "420px", style: "Fine Line" },
  { id: "t28", bg: "#2e2a27", alt: "Realistic eye inner arm",        height: "300px", style: "Realism" },
  { id: "t29", bg: "#1f1d1b", alt: "Fine line abstract back",        height: "260px", style: "Fine Line" },
  { id: "t30", bg: "#2c2825", alt: "Micro floral shin",              height: "440px", style: "Micro-realism" },
];
